# Generated by Django 3.2.7 on 2022-06-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_alter_reportes_options_alter_reportes_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportes',
            options={},
        ),
        migrations.AlterModelTable(
            name='reportes',
            table=None,
        ),
    ]
