# Generated by Django 3.2.7 on 2022-06-23 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_vehiculo', '0005_auto_20220618_2338'),
        ('tipo_accidente', '0007_alter_tipoaccidente_options'),
        ('reporte', '0004_auto_20220618_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='accidente',
        ),
        migrations.AddField(
            model_name='reportes',
            name='descripción',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reportes',
            name='tipo_accidente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_accidente.tipoaccidente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportes',
            name='tipo_vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_vehiculo.tipovehiculo'),
            preserve_default=False,
        ),
    ]
