# Generated by Django 4.0.5 on 2022-06-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_accidente', '0001_initial'),
        ('tipo_vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidentes',
            fields=[
                ('id_accidente', models.AutoField(primary_key=True, serialize=False)),
                ('descripción', models.CharField(max_length=500)),
                ('tipo_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_accidente.tipoaccidente')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_vehiculo.tipovehiculo')),
            ],
        ),
    ]
