# Generated by Django 4.0.5 on 2022-06-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidente', '0002_alter_accidentes_options_alter_accidentes_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accidentes',
            options={},
        ),
        migrations.AlterModelTable(
            name='accidentes',
            table=None,
        ),
    ]
