# Generated by Django 3.2.7 on 2022-06-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuarios_options_alter_usuarios_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
