# Generated by Django 3.2.7 on 2022-06-23 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0004_auto_20220618_2338'),
        ('usuario', '0004_auto_20220618_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rol.rol'),
            preserve_default=False,
        ),
    ]
