# Generated by Django 4.0.5 on 2022-06-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_accidente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoaccidente',
            options={'ordering': ['id_tipo_accidente'], 'verbose_name': 'Tipo Accidente', 'verbose_name_plural': 'Tipo Accidentes'},
        ),
        migrations.AlterModelTable(
            name='tipoaccidente',
            table='Tipo Accidentes',
        ),
    ]
