# Generated by Django 4.0.5 on 2022-06-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_accidente', '0003_alter_tipoaccidente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoaccidente',
            options={'ordering': ['id_tipo_accidente'], 'verbose_name': 'Tipo_Accidente', 'verbose_name_plural': 'Tipo_Accidentes'},
        ),
        migrations.AlterModelTable(
            name='tipoaccidente',
            table='Tipo_Accidentes',
        ),
    ]
