# Generated by Django 4.0.5 on 2022-06-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_accidente', '0004_alter_tipoaccidente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoaccidente',
            options={},
        ),
        migrations.AlterModelTable(
            name='tipoaccidente',
            table=None,
        ),
    ]
