# Generated by Django 3.2.7 on 2022-06-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_accidente', '0005_alter_tipoaccidente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoaccidente',
            options={'verbose_name': 'TipoAccidente', 'verbose_name_plural': 'TipoAccidentes'},
        ),
        migrations.AlterField(
            model_name='tipoaccidente',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
