# Generated by Django 4.0.5 on 2022-06-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0002_alter_municipios_options_alter_municipios_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipios',
            options={},
        ),
        migrations.AlterModelTable(
            name='municipios',
            table=None,
        ),
    ]
