# Generated by Django 3.2.7 on 2022-06-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0003_alter_municipios_options_alter_municipios_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipios',
            options={'ordering': ['id_municipios'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterField(
            model_name='municipios',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
