# Generated by Django 3.2.7 on 2022-06-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0005_remove_departamentos_municipios'),
        ('municipio', '0004_auto_20220618_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departamento.departamentos'),
            preserve_default=False,
        ),
    ]
