# Generated by Django 3.2.7 on 2022-06-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0005_municipios_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
