# Generated by Django 4.0.5 on 2022-06-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo Vehiculo', 'verbose_name_plural': 'Tipo Vehiculos'},
        ),
        migrations.AlterModelTable(
            name='tipovehiculo',
            table='Tipo Vehiculos',
        ),
    ]
