# Generated by Django 4.0.5 on 2022-06-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_vehiculo', '0002_alter_tipovehiculo_options_alter_tipovehiculo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo_Vehiculo', 'verbose_name_plural': 'Tipo_Vehiculos'},
        ),
        migrations.AlterModelTable(
            name='tipovehiculo',
            table='Tipo_Vehiculos',
        ),
    ]
