# Generated by Django 4.0.5 on 2022-06-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_vehiculo', '0003_alter_tipovehiculo_options_alter_tipovehiculo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={},
        ),
        migrations.AlterModelTable(
            name='tipovehiculo',
            table=None,
        ),
    ]
