# Generated by Django 3.2.7 on 2022-06-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamentos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={},
        ),
        migrations.AlterModelTable(
            name='departamentos',
            table=None,
        ),
    ]
