# Generated by Django 3.2.7 on 2022-06-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_auto_20220618_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='Municipios',
        ),
    ]
