# Generated by Django 4.0.5 on 2022-06-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['id_rol'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelTable(
            name='rol',
            table='Roles',
        ),
    ]
