# Generated by Django 3.2.7 on 2022-06-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_alter_rol_options_alter_rol_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterModelTable(
            name='rol',
            table=None,
        ),
    ]
